### ISSUE TITLE
Fixing MessageBodyWriter issues

### ISSUE THREAD

**Issue by StephanSST** [baloise/open-source#125]
Our Rest Service leads to Resteasy Exceptions like this:

`Caused by: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: ch.baloise.corellia.api.entities.ErrorResponse of media type: application/octet-stream
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:110)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:187)
        ... 56 more`

**Comment by StephanSST** [comment]
Wrong projects, correct project would be: https://github.com/baloise/corellia/issues/46
